apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val }}
    {{- end }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: grafana
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: grafana-ports-mtls-disabled
  namespace: {{ .Release.Namespace }}
spec:
  targets:
  - name: grafana
    ports:
    - number: {{ .Values.service.externalPort }}
---
