apiVersion: v1
name: mixer
version: 0.8.0
appVersion: 0.8.0
tillerVersion: ">=2.7.2"
description: Helm chart for mixer deployment
keywords:
  - istio
  - mixer
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
