apiVersion: v1
kind: Secret
metadata:
  name: kiali
  labels:
    app: kiali

type: Opaque
data:
  username: {{ .Values.dashboard.username | b64enc | quote }}
  password: {{ .Values.dashboard.password | b64enc | quote }}
